//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet4DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class statement
    {
        public int statementId { get; set; }
        public double temperature { get; set; }
        public double humidity { get; set; }
        public System.DateTime dateTime { get; set; }
        public int captorId { get; set; }
    
        public virtual captor captor { get; set; }
    }
}
